### ISSUE TITLE
Running error！！！[frontend] missing field `origin`

### ISSUE THREAD

**Issue by foosaa** [Hirevo/alexandrie#152]
# alexandrie.toml :
[general]
bind_address = "127.0.0.1:3000"

[frontend]
enabled = true
title = "Alexandrie"
description = "An alternative crate registry for Cargo, the Rust package manager."
links = [
    { name = "Github repository", href = "https://github.com/Hirevo/alexandrie" },
    { name = "User documentation", href = "https://hirevo.github.io/alexandrie" },
]

[frontend.sessions]
cookie_name = "alexandrie.sid"
secret = "YOU_REALLY_SHOULD_CHANGE_THIS_BEFORE_DEPLOYING"

[frontend.assets]
path = "assets"

[frontend.templates]
path = "templates"

[frontend.auth.local]
enabled = true
allow_registration = true

[frontend.auth.github]
enabled = false
client_id = "GITHUB_OAUTH_CLIENT_ID"
client_secret = "GITHUB_OAUTH_CLIENT_SECRET"

allowed_organizations = [
    # Using this organization does not requires any specific team membership.
    { name = "ORG_NAME_1" },
    # But using this one does requires membership in one of specified teams.
    { name = "ORG_NAME_2", allowed_teams = ["TEAM_NAME"] },
]
allow_registration = true

[frontend.auth.gitlab]
enabled = false
origin = "https://gitlab.com"
client_id = "GITLAB_OAUTH_CLIENT_ID"
client_secret = "GITLAB_OAUTH_CLIENT_SECRET"

allowed_groups = [
    "GROUP_1",
    "GROUP_2",
]
allow_registration = true

[database]
url = "alexandrie.db"

[index]
type = "command-line"
path = "crate-index"

[storage]
type = "disk"
path = "crate-storage"

[syntect.syntaxes]
type = "dump"
path = "syntect/dumps/syntaxes.dump"

[syntect.themes]
type = "dump"
path = "syntect/dumps/themes.dump"
theme_name = "frontier-contrast"

# Execute a command：
./target/debug/alexandrie -c alexandrie.toml

# Error occurs：
TOML error: TOML parse error at line 4, column 1
  |
4 | [frontend]
  | ^^^^^^^^^^
missing field `origin`

# How should I change it?

**Comment by Hirevo** [comment]
Hi,  
It seems that I missed to include a needed field in the example configuration.  
Please try to insert the following option to your `alexandrie.toml` file, and try again:
```toml
[frontend.auth]
# You need to replace this by the origin of the endpoint with which users will access your Alexandrie instance.
# This is needed for creating the correct `redirect_uri` for OAuth 2 authentication flows (currently: GitHub/GitLab).
# If you are not using GitHub or GitLab to authenticate, then this value will never be used and can be set to anything.
origin = "http://localhost:3000"
```

This should resolve your issue, feel free to comment here again if the error persists or if you encounter another configuration-related error.
