### ISSUE TITLE
Allow user to optionally specify a credentials file for databases

### ISSUE THREAD

**Issue by bmhenry** [Hirevo/alexandrie#30]
Currently, username & password are hard-coded into the database URL in `alexandrie.toml`.
Would it be possible to allow the user to specify a credentials file for the password?

For example:

```toml
[database]
url = "mysql://127.0.0.1:3306/alexandrie"
user = "alex"
password_file = "~/db_creds"
```

The credentials file could likely be a single line just containing the password.

This change would mostly open up Docker options. `mysql` and `postgres` docker containers already exist, and passwords can be passed to them via a file mounted as a secret. This would allow mounting that same password file in the Alexandrie container, avoiding writing the password in multiple places.
