### ISSUE TITLE
Add support for listening on AF_UNIX

### ISSUE THREAD

**Issue by jrb0001** [Hirevo/alexandrie#73]
AF_UNIX uses filesystem paths instead of address+port pairs for socket addresses which makes it much easier to avoid conflicts if you run multiple services on the same machine.

tide 0.12.0 seems to support it with the `http+unix:///path` scheme: https://docs.rs/tide/0.12.0/tide/listener/trait.ToListener.html#strings-supported-only-on-cfgunix-platforms

I am planning to run alexandrie behind a reverse-proxy (which also does TLS termination) so this would be a useful feature for me.

**Comment by Hirevo** [comment]
Hello, thanks for filing this issue.  

I agree that the configuration file right now is not flexible enough to permit this.  
I think I'll be fixing this, right after making the upgrade to Tide 0.12 (it is currently sitting on 0.10).  

And I think I'll be changing the configuration to go from this:
```toml
[general]
addr = "0.0.0.0"
port = 3000
```
to this:
```toml
[general]
bind_address = "0.0.0.0:3000"
# or
bind_address = "http+unix:///path"
# or any other address that Tide knows how to turn into a `Listener`
```
Would that correctly fit your use-case ?
