### ISSUE TITLE
Make UID and GID configurable

### ISSUE THREAD

**Issue by HugoPuntos** [Hirevo/alexandrie#95]
Hello,

The UID and SIG set to [1000](https://github.com/Hirevo/alexandrie/blob/master/Dockerfile#L74) can conflict with a user existing on the host running the containers. It could be handy to have control over their value.

Since these settings are managed by some args parameters, we could use the same mechanism as for the `DATABASE` arg and replace this [block](https://github.com/Hirevo/alexandrie/blob/master/docker-compose.yaml#L8):

```
build:
  context: .
  args:
    - DATABASE=${DATABASE}
```

by

```
build:
  context: .
  args:
    - DATABASE=${DATABASE}
    - GROUP_ID=${GROUP_ID}
    - USER_ID=${USER_ID}
```

Thanks,
Hugo
